### PR TITLE
suggestion: make location and tenant id optional

### PR DESCRIPTION
**Pull request by kewalaka**
This PR is a suggestion / illustration of the more specific question raised here:

https://github.com/Azure/Azure-Verified-Modules/issues/313

It allows the location & tenant id to have good defaults, simplifying the default example further, whilst still providing flexibility to the module consumer.

E2E test from my fork: https://github.com/kewalaka/terraform-azurerm-avm-res-keyvault-vault/actions/runs/7023774889

### CODE REVIEW

**Comment by kewalaka** [comment]
I realise as I checked the PR that I built this on stop of the regex change - apologies for the combined commit.  hopefully ok as primarily I'm sharing this as a discussion point.

**Comment by matt-FFFFFF** [comment]
Thanks for this @kewalaka we will discuss internally. I think this is a sensible suggestion.

**Comment by matt-FFFFFF** [comment]
Incidentally. The regex stuff I have worked on in the certificates feature branch. I've also added some unit tests too. Let me know what you think.

**Comment by kewalaka** [comment]
> Incidentally. The regex stuff I have worked on in the certificates feature branch. I've also added some unit tests too. Let me know what you think.

Very cool.  I was wondering how to handle the expected cases where examples should fail.

Had a similar [discussion](https://github.com/kewalaka/terraform-azurerm-avm-res-storage-storageaccount/issues/4) when i was working on converting the official storage account into one more like AVM.  I ended up [creating a repo to illustrate](https://github.com/kewalaka/terraform-storagecontainer-sharedkeys), but I like this much better.

**Comment by kewalaka** [comment]
closing as we with hindsight we don't want to introduce unnecessary data dependencies.

**Pull request closed without merging**
