### PR TITLE
fix: add missing tags to PE resource

### PR DESCRIPTION
**Pull request by b0bu**
Tagging policy in place requires PE resource be created with tags

### CODE REVIEW

**Comment by b0bu** [comment]
Any chance of this going through it's blocking me I'm going to need to fork if it can't be approved

**Comment by matt-FFFFFF** [comment]
Hey @b0bu thanks for this PR

I will create a new input for the specific tags for the PE resource. It's the standard for Azure Verified Modules.

I can do this in the next 24 hours

**Comment by matt-FFFFFF** [comment]
Apologies @b0bu you have implemented this correctly

**Review by matt-FFFFFF — APPROVED** [review]
LGTM

**Pull request merged**
